---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
# Repository of codes and data for "Analisis Koleksem Khas dan Potensinya untuk Kajian Kemiripan Makna Konstruksional dalam Bahasa Indonesia"

This is a repository for a forthcoming chapter in a Festschrift titled "E**tika** Bahasa: Buku Persembahan Menapaki Usia Pensiun I KETUT TIKA" and edited by I Nengah Sudipa (English Department, Udayana University, Indonesia).

## Authors

[Gede Primahadi Wijaya Rajeg](https://figshare.com/authors/Gede_Primahadi_Wijaya_Rajeg/1234749) & [I Made Rajeg](https://figshare.com/authors/I_Made_Rajeg/4052377)

## Licenses

The dataset for this project and the R Markdown source file for writing up the paper are licensed under the [Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)](https://creativecommons.org/licenses/by-nc-sa/4.0/). The embedded R codes within the R Markdown source file to run the statistical analysis are licensed under the [MIT License](https://github.com/gederajeg/analisis_koleksem_khas/blob/master/LICENSE).

## Abstract of the paper

### Indonesian

Makalah ini mengenalkan Analisis Koleksem Khas (*Distinctive Collexeme Analysis*) dan mengulas potensinya terhadap salah satu isu linguistik dalam Bahasa Indonesia (BI), yaitu persamaan/perbedaan semantis pasangan verba kausatif deajektiva sebagai pencontohan dua konstruksi kausatif morfologis ([*per-* + AJ] dan [AJ + *-kan*]), yang, menurut salah satu buku tatabahasa BI, perbedaan maknanya dianggap tidak begitu disadari oleh kebanyakan penutur BI. Dengan menggunakan pasangan kata _memperbesar_ dan _membesarkan_ sebagai contoh awal, ditemukan adanya perbedaan substansial berdasarkan distribusi dan tipe semantis koleksem R1 khas pada masing-masing verba. Lebih lanjut, koleksem khas kedua verba tersebut mencerminkan ciri semantis dominan yang dilandasi dengan dua metafora konseptual berbeda: (i) <span style = "font-variant:small-caps;">penting adalah besar</span> untuk _membesarkan_, dan (ii) metafora ikutan dari <span style = "font-variant:small-caps;">kuantitas adalah ukuran</span>, yaitu <span style = "font-variant:small-caps;">lebih (banyak) adalah besar</span>, untuk _memperbesar_.

*Kata kunci*: Linguistik Korpus Kuantitatif; Analisis Koleksem Khas; Korpus Bahasa Indonesia Leipzig; konstruksi kausatif morfologis Bahasa Indonesia; kemiripan makna; metafora konseptual

### English

This contribution introduces *Distinctive Collexeme Analysis* (DCA) and explores its potential to address a theoretical issue in Indonesian linguistics, namely semantic (dis)similarity between a pair of deadjectival causative verbs of the same root realising two causative morphological constructions, which, according to one of the Indonesian grammar textbooks, are assumed to be semantically indistinguishable by many Indonesian speakers; the constructions are [*per-* + ADJ] and [ADJ + *-kan*]. Using the pair of active-voiced verbs with the root *besar* 'big' (i.e. _memperbesar_ and _membesarkan_) as a preliminary example, we demonstrate that there are substantial distributional and semantic differences concerning the distinctive R1 collocates of these verbs. We argue that the predominant semantics of the verbs based on their distinctive collocates reflect two different metaphorical conceptualisations: (i) <span style = "font-variant:small-caps;">significant is big</span> for _membesarkan_, and (ii) the entailment of <span style = "font-variant:small-caps;">quantity is size</span> metaphor, namely <span style = "font-variant:small-caps;">more is big</span>, for _memperbesar_.

*Keywords*: Quantitative Corpus Linguistics; Distinctive Collexeme Analysis; Indonesian Leipzig Corpora; Indonesian morphological causative constructions; near-synonymy; conceptual metaphors


